"""empty message

Revision ID: 0592aa5dd09c
Revises: 
Create Date: 2025-09-26 05:51:59.517173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0592aa5dd09c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'candidates', ['candidate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answers')
        batch_op.drop_column('candidate_id')

    # ### end Alembic commands ###
