"""empty message

Revision ID: 51180468c954
Revises: f8141cffb58b
Create Date: 2025-09-26 10:29:39.014451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51180468c954'
down_revision = 'f8141cffb58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacancy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.drop_column('vacancy')

    # ### end Alembic commands ###
