"""empty message

Revision ID: f8141cffb58b
Revises: 0592aa5dd09c
Create Date: 2025-09-26 10:26:05.130818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8141cffb58b'
down_revision = '0592aa5dd09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitions', schema=None) as batch_op:
        batch_op.drop_column('published_on')

    # ### end Alembic commands ###
